// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubtwfukhwekoqlhfvioz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVidHdmdWtod2Vrb3FsaGZ2aW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMzIwNTYsImV4cCI6MjA1MDkwODA1Nn0.onIfyHwhZwSrKl6uTGUmcUcno6gWP_WIZdC8P34lFNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);